# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: id_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'id_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10id_service.proto\x12\x0f\x62mcp.id_service\"\x92\x01\n\x11GenerateIdRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1b\n\x13parent_canonical_id\x18\x04 \x01(\t\x12\x13\n\x0bparam_types\x18\x05 \x03(\t\x12\x15\n\rlanguage_hint\x18\x06 \x01(\t\"7\n\x12GenerateIdResponse\x12\x14\n\x0c\x63\x61nonical_id\x18\x01 \x01(\t\x12\x0b\n\x03gid\x18\x02 \x01(\t\"#\n\x0eParseIdRequest\x12\x11\n\tid_string\x18\x01 \x01(\t\"\xb5\x01\n\x0fParseIdResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1b\n\x13parent_canonical_id\x18\x04 \x01(\t\x12\x13\n\x0bparam_types\x18\x05 \x03(\t\x12\x14\n\x0c\x63\x61nonical_id\x18\x06 \x01(\t\x12\x17\n\x0flanguage_prefix\x18\x07 \x01(\t\x12\x0b\n\x03gid\x18\x08 \x01(\t2\xb0\x01\n\tIdService\x12U\n\nGenerateId\x12\".bmcp.id_service.GenerateIdRequest\x1a#.bmcp.id_service.GenerateIdResponse\x12L\n\x07ParseId\x12\x1f.bmcp.id_service.ParseIdRequest\x1a .bmcp.id_service.ParseIdResponseBC\n\x13\x63om.bmcp.id_serviceB\x0eIdServiceProtoP\x01Z\x1agithub.com/bmcp/id_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'id_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.bmcp.id_serviceB\016IdServiceProtoP\001Z\032github.com/bmcp/id_service'
  _globals['_GENERATEIDREQUEST']._serialized_start=38
  _globals['_GENERATEIDREQUEST']._serialized_end=184
  _globals['_GENERATEIDRESPONSE']._serialized_start=186
  _globals['_GENERATEIDRESPONSE']._serialized_end=241
  _globals['_PARSEIDREQUEST']._serialized_start=243
  _globals['_PARSEIDREQUEST']._serialized_end=278
  _globals['_PARSEIDRESPONSE']._serialized_start=281
  _globals['_PARSEIDRESPONSE']._serialized_end=462
  _globals['_IDSERVICE']._serialized_start=465
  _globals['_IDSERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
