# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import id_service_pb2 as id__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in id_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdServiceStub(object):
    """IdService provides centralized ID generation and parsing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateId = channel.unary_unary(
                '/bmcp.id_service.IdService/GenerateId',
                request_serializer=id__service__pb2.GenerateIdRequest.SerializeToString,
                response_deserializer=id__service__pb2.GenerateIdResponse.FromString,
                _registered_method=True)
        self.ParseId = channel.unary_unary(
                '/bmcp.id_service.IdService/ParseId',
                request_serializer=id__service__pb2.ParseIdRequest.SerializeToString,
                response_deserializer=id__service__pb2.ParseIdResponse.FromString,
                _registered_method=True)


class IdServiceServicer(object):
    """IdService provides centralized ID generation and parsing
    """

    def GenerateId(self, request, context):
        """GenerateId generates a canonical ID and GID for a given entity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseId(self, request, context):
        """ParseId parses a canonical ID or GID into its components
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateId': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateId,
                    request_deserializer=id__service__pb2.GenerateIdRequest.FromString,
                    response_serializer=id__service__pb2.GenerateIdResponse.SerializeToString,
            ),
            'ParseId': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseId,
                    request_deserializer=id__service__pb2.ParseIdRequest.FromString,
                    response_serializer=id__service__pb2.ParseIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bmcp.id_service.IdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bmcp.id_service.IdService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdService(object):
    """IdService provides centralized ID generation and parsing
    """

    @staticmethod
    def GenerateId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bmcp.id_service.IdService/GenerateId',
            id__service__pb2.GenerateIdRequest.SerializeToString,
            id__service__pb2.GenerateIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bmcp.id_service.IdService/ParseId',
            id__service__pb2.ParseIdRequest.SerializeToString,
            id__service__pb2.ParseIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
