import { AstNode, RelationshipInfo } from './parser';
import { createContextLogger } from '../utils/logger';
import path from 'path';
import winston from 'winston'; // Import winston type

const logger = createContextLogger('RelationshipResolver');

/**
 * Resolves placeholder relationships generated by the parser.
 */
export class RelationshipResolver {
    // Index nodes by their stable entityId for efficient lookup
    private nodeEntityIndex: Map<string, AstNode> = new Map();
    // Index nodes by name (can have multiple nodes with the same name)
    private nodesByName: Map<string, AstNode[]> = new Map();
    // Index nodes by file path using entityId
    private nodesByFilePath: Map<string, AstNode[]> = new Map();
    // Keep track of exports per file (file entityId -> Set<entityId of exported nodes>)
    private exportsByFile: Map<string, Set<string>> = new Map();
    // Store relationships passed to resolve() locally for lookups
    private currentRelationships: RelationshipInfo[] = [];

    constructor() {
        logger.info('RelationshipResolver initialized');
    }

    /**
     * Reset the resolver state for a new analysis run.
     */
    reset(): void {
        this.nodeEntityIndex.clear();
        this.nodesByName.clear();
        this.nodesByFilePath.clear();
        this.exportsByFile.clear();
        this.currentRelationships = [];
        logger.debug('RelationshipResolver state reset');
    }

    /**
     * Build internal indexes from the parsed nodes.
     */
    buildIndexes(nodes: AstNode[]): void {
        logger.info(`Building indexes for ${nodes.length} nodes...`);
        this.reset(); // Ensure clean state before building
        for (const node of nodes) {
            if (!node || !node.entityId) {
                logger.warn('Attempted to index invalid node:', { node });
                continue;
            }
            this.nodeEntityIndex.set(node.entityId, node);

            if (!this.nodesByName.has(node.name)) {
                this.nodesByName.set(node.name, []);
            }
            this.nodesByName.get(node.name)!.push(node);

            if (!this.nodesByFilePath.has(node.filePath)) {
                this.nodesByFilePath.set(node.filePath, []);
            }
            this.nodesByFilePath.get(node.filePath)!.push(node);
        }
        logger.info('Node indexes built successfully.');
    }

    /**
     * Pre-process relationships to build the export map.
     */
    private buildExportMap(relationships: RelationshipInfo[]): void {
        logger.debug('Building export map...');
        this.exportsByFile.clear();
        for (const rel of relationships) {
            if (rel.type === 'EXPORTS') {
                const sourceFileNode = this.nodeEntityIndex.get(rel.sourceId);
                const targetNode = this.nodeEntityIndex.get(rel.targetId);
                if (sourceFileNode && targetNode) {
                    if (!this.exportsByFile.has(sourceFileNode.entityId)) {
                        this.exportsByFile.set(sourceFileNode.entityId, new Set());
                    }
                    if (targetNode.kind !== 'File') {
                         this.exportsByFile.get(sourceFileNode.entityId)!.add(targetNode.entityId);
                    }
                } else {
                    logger.debug(`Could not find source/target node for EXPORTS relationship`, { relId: rel.id });
                }
            }
        }
         logger.debug(`Export map built for ${this.exportsByFile.size} files.`);
    }


    /**
     * Resolves placeholder relationships using the built indexes.
     */
    resolve(relationships: RelationshipInfo[]): RelationshipInfo[] {
        logger.info(`Attempting to resolve ${relationships.length} relationships...`);
        this.currentRelationships = relationships;
        this.buildExportMap(relationships);

        const resolvedRelationships: RelationshipInfo[] = [];
        let resolvedCount = 0;
        let unresolvedCount = 0;

        for (const rel of relationships) {
            if (!rel.properties?.isPlaceholder) {
                if (this.nodeEntityIndex.has(rel.sourceId) && this.nodeEntityIndex.has(rel.targetId)) {
                    resolvedRelationships.push(rel);
                } else {
                     logger.warn(`Non-placeholder relationship references non-indexed node(s)`, { relId: rel.id, sourceId: rel.sourceId, targetId: rel.targetId });
                     unresolvedCount++;
                }
                continue;
            }

            const sourceNode = this.nodeEntityIndex.get(rel.sourceId);
            if (!sourceNode) {
                logger.warn(`Cannot resolve relationship, source node not found in index`, { relId: rel.id, sourceId: rel.sourceId, targetHint: rel.properties?.targetName || rel.targetId });
                unresolvedCount++;
                continue;
            }

            // Pass logger to findTargetNode for detailed logging
            const targetNode = this.findTargetNode(sourceNode, rel, logger);

            if (targetNode) {
                const isCrossFile = sourceNode.filePath !== targetNode.filePath;
                const baseRelType = typeof rel.type === 'string' ? rel.type.replace('CROSS_FILE_', '') : 'UNKNOWN';
                const finalRelType = isCrossFile ? `CROSS_FILE_${baseRelType}` : baseRelType;
                const targetIdentifier = rel.properties?.targetMemberName ? `${targetNode.entityId}.${rel.properties.targetMemberName}` : targetNode.entityId;
                const finalRelEntityId = this.generateEntityId(finalRelType, `${sourceNode.entityId}:${targetIdentifier}`);
                const now = new Date().toISOString();

                resolvedRelationships.push({
                    ...rel,
                    id: this.generateId(finalRelType, `${sourceNode.id}:${targetNode.id}`),
                    entityId: finalRelEntityId,
                    type: finalRelType,
                    targetId: targetNode.entityId,
                    createdAt: rel.createdAt,
                    properties: {
                        ...rel.properties,
                        isPlaceholder: false,
                        resolutionMethod: rel.properties?.resolutionMethod || 'unknown',
                        originalTargetId: rel.targetId,
                        resolvedAt: now,
                    },
                });
                resolvedCount++;
            } else {
                // Log final failure at debug level
                logger.debug(`Failed to resolve placeholder target after all steps`, {
                    relId: rel.id,
                    source: sourceNode.entityId,
                    targetHint: rel.properties?.targetName || rel.properties?.qualifiedName || rel.targetId,
                    relType: rel.type
                 });
                unresolvedCount++;
            }
        }

        logger.info(`Resolution complete: ${resolvedCount} resolved, ${unresolvedCount} unresolved.`);
        return resolvedRelationships;
    }

    /**
     * Tries to find the target node for a placeholder relationship.
     * If the target is a property, it returns the containing Class/Interface node.
     */
    private findTargetNode(sourceNode: AstNode, placeholderRel: RelationshipInfo, logger: winston.Logger): AstNode | null {
        const targetEntityId = placeholderRel.targetId;
        const targetName = placeholderRel.properties?.targetName;
        const qualifiedNameHint = placeholderRel.properties?.qualifiedName;
        const expectsProperty = this.relationshipExpectsProperty(placeholderRel.type);
        const relType = placeholderRel.type;
        const logMeta = { relId: placeholderRel.id, source: sourceNode.entityId, targetHint: targetName || qualifiedNameHint || targetEntityId, relType };

        logger.debug(`Resolving placeholder`, logMeta);

        // 1. Direct Entity ID match
        let target = this.nodeEntityIndex.get(targetEntityId);
        if (target) {
            if (expectsProperty && (target.kind === 'Class' || target.kind === 'Interface')) {
                 const memberProp = target.memberProperties?.find(p => p.name === targetName);
                 if (memberProp) {
                     placeholderRel.properties = { ...placeholderRel.properties, resolutionMethod: 'direct_entity_id_member', targetMemberName: memberProp.name };
                     logger.debug(`Resolved via direct_entity_id_member`, logMeta);
                     return target; // Return container
                 } else {
                     logger.debug(`Direct entity ID match found (${target.entityId}), but expected property '${targetName}' not found in memberProperties.`, logMeta);
                 }
            } else if (!expectsProperty || this.matchesExpectedKind(target, relType)) {
                 placeholderRel.properties = { ...placeholderRel.properties, resolutionMethod: 'direct_entity_id' };
                 logger.debug(`Resolved via direct_entity_id`, logMeta);
                 return target;
            } else {
                 logger.debug(`Direct entity ID match found (${target.entityId}), but failed kind check (expected property=${expectsProperty}, node kind=${target.kind}).`, logMeta);
            }
        } else {
             logger.debug(`Step 1 (Direct ID) failed: No node found for entityId ${targetEntityId}`, {
                 ...logMeta,
                 reason: `Node with entityId ${targetEntityId} not in index.`
             });
        }

        // 2. Name match within the same file (including member properties)
        if (targetName) {
            const sameFileNodes = this.nodesByFilePath.get(sourceNode.filePath) || [];
            target = sameFileNodes.find(n => n.name === targetName && this.matchesExpectedKind(n, relType));
            if (target) {
                 placeholderRel.properties = { ...placeholderRel.properties, resolutionMethod: 'same_file_name' };
                 logger.debug(`Resolved via same_file_name`, logMeta);
                 return target;
            }
            if (expectsProperty) {
                const parentContainers = sameFileNodes.filter(n => n.kind === 'Class' || n.kind === 'Interface');
                for(const container of parentContainers) {
                    const memberProp = container.memberProperties?.find(p => p.name === targetName);
                    if (memberProp) {
                        placeholderRel.properties = { ...placeholderRel.properties, resolutionMethod: 'same_file_member', targetMemberName: memberProp.name };
                        logger.debug(`Resolved via same_file_member to container ${container.entityId}`, logMeta);
                        return container;
                    }
                }
            }
             logger.debug(`Step 2 (Same File) failed: No node or member named '${targetName}' found in ${sourceNode.filePath}`, {
                 ...logMeta,
                 filePath: sourceNode.filePath,
                 reason: `No matching node or member property found by name.`
             });
        } else {
             logger.debug(`Step 2 (Same File) skipped: No targetName provided.`, logMeta);
        }

        // 3. Name match in imported files (check exports, including member properties)
        if (targetName) {
            const fileImports = this.getImportedFilePaths(sourceNode.filePath);
            let checkedImportPaths = false;
            for (const importPath of fileImports) {
                 checkedImportPaths = true;
                 const resolvedImportPath = importPath.startsWith('.') ? path.resolve(path.dirname(sourceNode.filePath), importPath).replace(/\\/g, '/') : importPath;
                 const importedFileNodes = this.nodesByFilePath.get(resolvedImportPath) || [];

                 target = importedFileNodes.find(n =>
                     n.name === targetName &&
                     this.matchesExpectedKind(n, relType) &&
                     this.exportsByFile.get(n.entityId)?.has(n.entityId)
                 );
                 if (target) {
                      placeholderRel.properties = { ...placeholderRel.properties, resolutionMethod: 'imported_file_name' };
                      logger.debug(`Resolved via imported_file_name from ${resolvedImportPath}`, logMeta);
                      return target;
                 }
                 if (expectsProperty) {
                     const importedContainers = importedFileNodes.filter(n => n.kind === 'Class' || n.kind === 'Interface');
                     for(const container of importedContainers) {
                         if (this.exportsByFile.get(container.entityId)?.has(container.entityId)) {
                             const memberProp = container.memberProperties?.find(p => p.name === targetName);
                             if (memberProp) {
                                 placeholderRel.properties = { ...placeholderRel.properties, resolutionMethod: 'imported_file_member', targetMemberName: memberProp.name };
                                 logger.debug(`Resolved via imported_file_member to container ${container.entityId} from ${resolvedImportPath}`, logMeta);
                                 return container;
                             }
                         }
                     }
                 }
            }
             if (checkedImportPaths) {
                  logger.debug(`Step 3 (Imports) failed: No exported node or member named '${targetName}' found in imports.`, {
                      ...logMeta,
                      checkedPaths: Array.from(fileImports),
                      reason: `No exported node or member property found by name in imported files.`
                  });
             } else {
                  logger.debug(`Step 3 (Imports) skipped: No imports found for source file.`, logMeta);
             }
        } else {
             logger.debug(`Step 3 (Imports) skipped: No targetName provided.`, logMeta);
        }

        // 4. General name match across all nodes (lower confidence, check members last)
        if (targetName) {
            const potentialTargets = this.nodesByName.get(targetName) || [];
            target = potentialTargets.find(n => this.matchesExpectedKind(n, relType));
             if (target) {
                 placeholderRel.properties = { ...placeholderRel.properties, resolutionMethod: 'global_name' };
                 logger.debug(`Resolved via global_name`, logMeta);
                 return target;
             }
             if (expectsProperty) {
                 for(const container of Array.from(this.nodeEntityIndex.values()).filter(n => n.kind === 'Class' || n.kind === 'Interface')) {
                     const memberProp = container.memberProperties?.find(p => p.name === targetName);
                     if (memberProp) {
                         placeholderRel.properties = { ...placeholderRel.properties, resolutionMethod: 'global_member', targetMemberName: memberProp.name };
                         logger.debug(`Resolved via global_member to container ${container.entityId}`, logMeta);
                         return container;
                     }
                 }
             }
             logger.debug(`Step 4 (Global) failed: No node or member named '${targetName}' found globally.`, {
                 ...logMeta,
                 reason: `No matching node or member property found by name across all indexed nodes.`
             });
        } else {
             logger.debug(`Step 4 (Global) skipped: No targetName provided.`, logMeta);
        }

        // Log final failure at DEBUG level now
        logger.debug(`Failed to resolve placeholder target after all steps`, logMeta);
        logger.debug(`Failed to resolve placeholder target after all steps`, {
            ...logMeta,
            sourceNodeInfo: { kind: sourceNode.kind, path: sourceNode.filePath, name: sourceNode.name },
            targetInfo: placeholderRel.properties || 'No properties',
            reason: "All resolution steps (Direct ID, Same File, Imports, Global) failed."
        });
        return null;
    }


    /**
     * Checks if a relationship type typically targets a property (now stored as metadata).
     */
    private relationshipExpectsProperty(relType: string): boolean {
        const baseRelType = relType.replace('CROSS_FILE_', '');
        // Only USES and MUTATES_STATE might target properties directly
        return baseRelType === 'USES' || baseRelType === 'MUTATES_STATE';
    }

    /**
     * Checks if a node's kind matches the expected target kind for a relationship type.
     * Updated for properties being metadata.
     */
    private matchesExpectedKind(node: AstNode, relType: string): boolean {
        const baseRelType = relType.replace('CROSS_FILE_', '');
        switch (baseRelType) {
            case 'CALLS': return node.kind === 'Function' || node.kind === 'Method';
            case 'USES': return ['Variable', 'Parameter', 'Function', 'Method', 'Class', 'Interface', 'TypeAlias'].includes(node.kind);
            case 'EXTENDS': return node.kind === 'Class' || node.kind === 'Interface';
            case 'IMPLEMENTS': return node.kind === 'Interface';
            case 'IMPORTS': return node.kind === 'File';
            case 'EXPORTS': return true;
            case 'MUTATES_STATE': return node.kind === 'Class' || node.kind === 'Interface' || node.kind === 'Variable';
            default: return true;
        }
    }

     /**
     * Retrieves the set of file paths imported by a given file.
     */
    private getImportedFilePaths(sourceFilePath: string): Set<string> {
        const sourceFileNode = Array.from(this.nodeEntityIndex.values()).find((n: AstNode) => n.kind === 'File' && n.filePath === sourceFilePath);
        if (!sourceFileNode) return new Set();

        return new Set(
            this.currentRelationships
                .filter((r: RelationshipInfo) => r.type === 'IMPORTS' && r.sourceId === sourceFileNode.entityId && r.properties?.importPath)
                .map((r: RelationshipInfo) => r.properties!.importPath as string)
        );
    }


    // Use the same ID generation logic as the parser for consistency
    private generateEntityId(prefix: string, qualifiedName: string): string {
        const safeIdentifier = qualifiedName.replace(/\\/g, '/').replace(/[^a-zA-Z0-9_.:/-]/g, '_');
        return `${prefix}:${safeIdentifier}`;
    }

    // Note: This generateId is slightly different from the one in parser.ts now,
    // as it doesn't have access to the per-file instance counter.
    private generateId(prefix: string, identifier: string, options: { line?: number; column?: number } = {}): string {
        const safeIdentifier = identifier.replace(/\\/g, '/').replace(/[^a-zA-Z0-9_.:/-]/g, '_');
        let contextSuffix = '';
        if (options.line !== undefined) contextSuffix += `:L${options.line}`;
        if (options.column !== undefined) contextSuffix += `:C${options.column}`;
        // Counter is NOT available here, potential for collision across files in same batch
        const id = `${prefix}:${safeIdentifier}${contextSuffix}`;
        return id;
    }
}

// Export singleton instance
export default new RelationshipResolver();